"""Common data structures and functions used across modules"""

# Define constants or shared functions here
COLORS = ['red', 'blue', 'green', 'yellow', 'black', 'orange', 'white', 'purple', 'wild']

CITIES = ["Seattle", "Portland", "Vancouver", "Calgary", "Winnipeg", "Helena", "Salt Lake City", "Phoenix", "El Paso", "Santa Fe", "Las Vegas",
          "Houston", "Dallas", "Oklahoma City", "Kansas City", "Omaha", "Duluth", "Sault St Marie", "Toronto", "Montreal", "Boston", "Pittsburgh",
          "Saint Louis", "Little Rock", "New Orleans", "Atlanta", "Nashville", "Raleigh", "Charleston", "Washington", "", "San Francisco",
          "Los Angeles", "Denver", "Chicago", "New York", "Miami"]

ROUTES = [
    ("Seattle", "Portland", 1, "any", True),
    ("Seattle", "Calgary", 4, "any"),
    ("Seattle", "Helena", 6, "yellow"),
    ("Seattle", "Vancouver", 1, "any", True),
    ("Calgary", "Vancouver", 3, "any"),
    ("Calgary", "Helena", 4, "any"),
    ("Calgary", "Winnipeg", 6, "white"),
    ("Portland", "San Francisco", 5, "green", True),
    ("Portland", "San Francisco", 5, "pink", True),
    ("Portland", "Salt Lake City", 6, "blue"),
    ("San Francisco", "Los Angeles", 3, "pink", True),
    ("San Francisco", "Los Angeles", 3, "yellow", True),
    ("San Francisco", "Salt Lake City", 5, "orange", True),
    ("San Francisco", "Salt Lake City", 5, "white", True),
    ("Salt Lake City", "Las Vegas", 3, "orange"),
    ("Salt Lake City", "Helena", 3, "pink"),
    ("Salt Lake City", "Denver", 3, "red", True),
    ("Salt Lake City", "Denver", 3, "yellow", True),
    ("Los Angeles", "Las Vegas", 2, "any"),
    ("Los Angeles", "Phoenix", 3, "any"),
    ("Los Angeles", "El Paso", 6, "black"),
    ("Phoenix", "Denver", 5, "white"),
    ("Phoenix", "Santa Fe", 3, "any"),
    ("Phoenix", "El Paso", 3, "any"),
    ("El Paso", "Houston", 6, "green"),
    ("El Paso", "Dallas", 4, "red"),
    ("El Paso", "Oklahoma City", 5, "yellow"),
    ("El Paso", "Santa Fe", 2, "any"),
    ("Denver", "Santa Fe", 2, "any"),
    ("Oklahoma City", "Santa Fe", 3, "blue"),
    ("Oklahoma City", "Denver", 4, "red"),
    ("Oklahoma City", "Little Rock", 2, "any"),
    ("Oklahoma City", "Kansas City", 2, "any", True),
    ("Oklahoma City", "Dallas", 2, "any", True),
    ("Denver", "Kansas City", 4, "black", True),
    ("Denver", "Kansas City", 4, "orange", True),
    ("Denver", "Omaha", 4, "pink"),
    ("Denver", "Helena", 4, "green"),
    ("Helena", "Winnipeg", 4, "blue"),
    ("Helena", "Duluth", 6, "orange"),
    ("Helena", "Omaha", 5, "red"),
    ("Duluth", "Winnipeg", 4, "black"),
    ("Winnipeg", "Sault St Marie", 6, "any"),
    ("Duluth", "Sault St Marie", 3, "any"),
    ("Duluth", "Toronto", 6, "pink"),
    ("Duluth", "Chicago", 3, "red"),
    ("Duluth", "Omaha", 2, "any", True),
    ("Toronto", "Sault St Marie", 2, "any"),
    ("Montreal", "Sault St Marie", 5, "black"),
    ("Toronto", "Montreal", 3, "any"),
    ("Toronto", "Pittsburgh", 2, "any"),
    ("Toronto", "Chicago", 4, "white"),
    ("Chicago", "Pittsburgh", 3, "orange", True),
    ("Chicago", "Pittsburgh", 3, "black", True),
    ("Chicago", "Saint Louis", 2, "green", True),
    ("Chicago", "Saint Louis", 2, "white", True),
    ("Chicago", "Omaha", 4, "blue"),
    ("Saint Louis", "Kansas City", 2, "blue", True),
    ("Saint Louis", "Kansas City", 2, "pink", True),
    ("Saint Louis", "Little Rock", 2, "any"),
    ("Saint Louis", "Nashville", 2, "any"),
    ("Saint Louis", "Pittsburgh", 5, "green"),
    ("Omaha", "Kansas City", 1, "any", True),
    ("Houston", "Dallas", 1, "any", True),
    ("Houston", "New Orleans", 2, "any"),
    ("Little Rock", "New Orleans", 3, "green"),
    ("Little Rock", "Nashville", 3, "white"),
    ("Little Rock", "Dallas", 2, "any"),
    ("Atlanta", "Nashville", 1, "any"),
    ("Atlanta", "Raleigh", 2, "any", True),
    ("Atlanta", "Charleston", 2, "any"),
    ("Atlanta", "Miami", 5, "blue"),
    ("Atlanta", "New Orleans", 4, "yellow", True),
    ("Atlanta", "New Orleans", 4, "orange", True),
    ("Miami", "New Orleans", 6, "red"),
    ("Miami", "Charleston", 4, "pink"),
    ("Raleigh", "Charleston", 2, "any"),
    ("Raleigh", "Washington", 2, "any", True),
    ("Raleigh", "Pittsburgh", 2, "any"),
    ("Raleigh", "Nashville", 3, "black"),
    ("Pittsburgh", "Nashville", 4, "yellow"),
    ("New York", "Washington", 2, "orange", True),
    ("New York", "Washington", 2, "black", True),
    ("New York", "Pittsburgh", 2, "white", True),
    ("New York", "Pittsburgh", 2, "green", True),
    ("New York", "Boston", 2, "yellow", True),
    ("New York", "Boston", 2, "red", True),
    ("New York", "Montreal", 3, "blue"),
    ("Boston", "Montreal", 2, "any", True),
    ("Pittsburgh", "Washington", 2, "any"),
]